# C:\master-proxy-infra\docker-compose.yml
# This network is the bridge between the master proxy and all applications.
# It MUST be created manually on the server once: `docker network create master_proxy_network`
networks:
  master_proxy_network:
    external: true
services:
  master-proxy:
    image: nginx:alpine
    container_name: master_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" # Make sure this port is published
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # --- ADD THIS LINE TO MOUNT THE CERTIFICATES ---
      - ./certs:/etc/nginx/certs:ro
    networks:
      - master_proxy_network
