version: "3.9"

# This network is the bridge between the master proxy and all applications.
# It MUST be created manually on the server once: `docker network create master_proxy_network`
networks:
  master_proxy_network:
    external: true

services:
  master-proxy:
    image: nginx:alpine
    container_name: master_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" # We'll set up SSL later, but reserve the port.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # This volume is for SSL certificates (e.g., from Let's Encrypt)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - master_proxy_network
