services:
  master-proxy:
    image: nginx:alpine
    container_name: master_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" # Make sure this port is published
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # --- ADD THIS LINE TO MOUNT THE CERTIFICATES ---
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - master_proxy_network
